# Generated by Django 4.0.6 on 2022-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='post/images/download.jpg', null=True, upload_to='post/images'),
        ),
    ]
