name: Auto PR from Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        
        with:
          token: ${{ secrets.SIGNING_TOKEN }}
          base: main
          head: dev
          title: "Auto PR: Dev → Main"
          body: "This PR is automatically created from dev branch."
